### ISSUE TITLE
Tipo de lista que retorna el método getAll() de DegreeService

### ISSUE THREAD

**Issue by juliancastro18** [gussiciliano/ghsicilianotfi#14]
El método debería devolver una lista de tipo DegreeModel en vez de Degree.

Lo modifiqué de la siguiente manera, será correcto?
![MetodoGetAll](https://user-images.githubusercontent.com/70178896/117191708-426d1e80-adb7-11eb-9e11-33ff33c136d7.png)

**Comment by gussiciliano** [comment]
Julian, perdón por las demora, es correcto :) a fines prácticos quedó más simple en el proyecto, pero es correcto :)
